### PR TITLE
fix: Don't send durations when they are not from actual capture times

### LINKED ISSUE #249: sometimes event duration is < 0
Should we add an extra check in here for other goofiness like request timestamp being greater than response timestamp? Something like `if eventDuration < 0 { eventDuration = 0 }`

_Originally posted by @JamieDanielson in https://github.com/honeycombio/honeycomb-network-agent/pull/179#discussion_r1326044898_
            

When a timestamp is missing it is still possible to get negative durations. Ideally we have a proper matching  so this doesn't happen... but if it does, we should probably set duration to 0 to avoid skewing correct durations.

negativedurations

### PR DESCRIPTION
**Pull request by robbkidd**
## Which problem is this PR solving?

- Closes #249 

## Short description of the changes

- refactor duration computation into an extracted function
- test drive timestamp(s) set/unset scenarios

## How to verify that this has the expected result

Duration is only set if both timestamps are present. If one or both are missing, attributes are added to the event indicating that, and no duration is set (event timestamp is set to time.now). If both timestamps are present, calculate the duration and add to the event. We should see no more negative durations caused by missing timestamps

### CODE REVIEW

File: handlers/libhoney_event_handler.go [hunk 1]
```diff
@@ -86,40 +86,53 @@ func initLibhoney(config config.Config, version string) func() {
...
+		honeyEvent.AddField("meta.timestamps_missing", "request, response")
+		honeyEvent.Timestamp = time.Now()
+
+	case httpEvent.RequestTimestamp.IsZero():
+		// no request
+		honeyEvent.AddField("meta.timestamps_missing", "request")
+		// but we have a response
+		honeyEvent.Timestamp = httpEvent.ResponseTimestamp
+		honeyEvent.AddField("http.response.timestamp", httpEvent.ResponseTimestamp)
+		honeyEvent.AddField("meta.httpEvent_response_handled_latency_ms", time.Since(httpEvent.ResponseTimestamp).Milliseconds())
```
Comment (robbkidd) [inline handlers/libhoney_event_handler.go:108]:
```suggestion
		honeyEvent.AddField("meta.response.capture_to_handle.latency_ms", time.Since(httpEvent.ResponseTimestamp).Milliseconds())
```

I don't know which.

File: handlers/libhoney_event_handler.go [hunk 2]
```diff
@@ -86,40 +86,53 @@ func initLibhoney(config config.Config, version string) func() {
...
 }
 
+// setTimestampsAndDurationIfValid sets time-related fields in the emitted telemetry
+// about the request/response cycle.
+//
+// It only sets timestamps if they are present in the captured event, and only
+// computes and includes durations for which there are correct timestamps to based them upon.
+func setTimestampsAndDurationIfValid(honeyEvent *libhoney.Event, httpEvent assemblers.HttpEvent) {
+	honeyEvent.AddField("meta.httpEvent_handled_at", time.Now())
+	switch true {
```
Comment (MikeGoldsmith) [inline handlers/libhoney_event_handler.go:96]:
```suggestion
	switch {
```

File: handlers/libhoney_event_handler.go [hunk 3]
```diff
@@ -86,40 +86,53 @@ func initLibhoney(config config.Config, version string) func() {
...
+		honeyEvent.AddField("duration_ms", httpEvent.ResponseTimestamp.Sub(httpEvent.RequestTimestamp).Milliseconds())
+	}
+}
+
+// handleEvent transforms a captured httpEvent into a libhoney event and sends it
 func (handler *libhoneyEventHandler) handleEvent(event assemblers.HttpEvent) {
-	// create libhoney event
-	ev := libhoney.NewEvent()
+	// the telemetry event to send
+	var ev *libhoney.Event = libhoney.NewEvent()
```
Comment (MikeGoldsmith) [inline handlers/libhoney_event_handler.go:131]:
```suggestion
	ev = libhoney.NewEvent()
```

File: handlers/libhoney_event_handler.go (hunk 1 above)
Comment (MikeGoldsmith) [reply handlers/libhoney_event_handler.go:108]: I like these better than having httpEvent in the name.

**Review by MikeGoldsmith — APPROVED** [review]
Generally looks good. Added a couple of minor suggestions around styling.

File: handlers/libhoney_event_handler.go (hunk 3 above)
Comment (robbkidd) [reply handlers/libhoney_event_handler.go:131]: Sooo, I threw `var …` in there purely a trick to help the human reading this code later to differentiate between all the things we've got that are variously event-flavored. I like this feature and propose that we keep it, but it's not a hill I'll even be maimed much less die on. I recognize that this is not a popular idiom, but what even _are_ idioms, anyway?

VS Code and [the Go extension](https://marketplace.visualstudio.com/items?itemName=golang.go) currently displays the comment above an explicit variable declaration in a floaty box that appears whenever the mouse hovers over the variable.

Screenshot 2023-10-03 at 12 08 10 PM

An implicit variable declaration does not trigger the Go extension to include a comment (either above or inline) for the variable.

Screenshot 2023-10-03 at 12 07 44 PM

File: handlers/libhoney_event_handler.go (hunk 1 above)
Comment (JamieDanielson) [reply handlers/libhoney_event_handler.go:108]: Agreed! Updating now to these new fields... and we can rename [again] in the future if needed 😅

**Review by JamieDanielson — APPROVED** [review]
those terms are satisfactory
